name: npm-publish
on:
    push:
        tags:
            - v*.*.*

jobs:
    npm-publish:
        name: npm-publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - run: yarn
            - name: eslint check
              run: npm run test:lint
            - run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
